import type { PromptConfig } from './types';

export const prompts: Record<string, PromptConfig> = {
  '1': {
    name: 'Meta Description - Single Page',
    description: "Paste the URL and optional context - we'll create optimized meta descriptions",
    iconName: 'FileText',
    category: 'meta',
    fields: [
      { id: 'url', label: 'Page URL *', placeholder: 'e.g., https://dgtraining.com/iata-training/', required: true },
      { id: 'focusKeyphrase', label: 'Focus Keyphrase (optional)', placeholder: 'e.g., iata certification online', required: false },
      { id: 'pageDescription', label: 'Additional Context (optional)', placeholder: 'e.g., emphasize group discounts, target FedEx shippers', multiline: true, rows: 2, required: false },
    ],
  },
  '2': {
    name: 'Meta Description - Batch',
    description: 'Paste multiple URLs (one per line) for batch processing',
    iconName: 'Briefcase',
    category: 'meta',
    fields: [
      { id: 'urls', label: 'Page URLs (one per line) *', placeholder: 'https://dgtraining.com/iata-training/\nhttps://dgtraining.com/dot-training/', multiline: true, rows: 6, required: true },
    ],
  },
  '3': {
    name: 'Meta Description - From Scratch',
    description: 'Create meta descriptions without a URL - describe your page and keywords',
    iconName: 'FileText',
    category: 'meta',
    fields: [
      { id: 'pageTitle', label: 'Page Title *', placeholder: 'e.g., IATA Dangerous Goods Training', required: true },
      { id: 'focusKeyphrase', label: 'Focus Keyphrase *', placeholder: 'e.g., iata certification online', required: true },
      { id: 'pageDescription', label: 'What is this page about? *', placeholder: 'e.g., Online IATA DG training, Category 6 certification', multiline: true, rows: 3, required: true },
      { id: 'targetKeywords', label: 'Additional Keywords (optional)', placeholder: 'e.g., dangerous goods training, dg certificate', required: false },
    ],
  },
  '4': {
    name: 'FAQ Section - Customer Questions',
    description: 'Create FAQ section based on actual customer questions',
    iconName: 'HelpCircle',
    category: 'faq',
    fields: [
      { id: 'businessType', label: 'Business Type', placeholder: 'Dangerous Goods Training Provider', defaultValue: 'Dangerous Goods Training Provider', required: false },
      { id: 'serviceProduct', label: 'Service/Product *', placeholder: 'e.g., IATA, IMDG, DOT Hazmat training courses', multiline: true, required: true },
      { id: 'questions', label: 'Customer Questions (one per line) *', placeholder: 'How long is the IATA DG certification valid?\nDo I need recurrent training?', multiline: true, rows: 6, required: true },
      { id: 'keywords', label: 'SEO Keywords to Include *', placeholder: 'e.g., IATA certification, hazmat recurrent training', multiline: true, required: true },
    ],
  },
  '5': {
    name: 'FAQ Content - Specific Topic',
    description: 'Build comprehensive FAQs around a specific topic',
    iconName: 'HelpCircle',
    category: 'faq',
    fields: [
      { id: 'topic', label: 'Main Topic *', placeholder: 'e.g., IATA Dangerous Goods Regulations', required: true },
      { id: 'audience', label: 'Target Audience *', placeholder: 'e.g., Freight forwarders seeking certification', required: true },
      { id: 'keywords', label: 'Keywords to Include *', placeholder: 'e.g., DGR, dangerous goods declaration', multiline: true, required: true },
      { id: 'competitorQuestions', label: 'Common Questions *', placeholder: 'e.g., What is covered in IATA training?', multiline: true, required: true },
    ],
  },
  '6': {
    name: 'Content Analysis & Improvement',
    description: 'Review existing content and get SEO improvement recommendations',
    iconName: 'RefreshCw',
    category: 'content',
    fields: [
      { id: 'contentUrl', label: 'Page URL (optional)', placeholder: 'e.g., https://dgtraining.com/iata-training/', required: false },
      { id: 'content', label: 'Current Content (optional if URL provided)', placeholder: 'Paste your existing webpage content...', multiline: true, rows: 8, required: false },
      { id: 'primaryKeyword', label: 'Primary Keyword (optional)', placeholder: 'e.g., IATA dangerous goods training', required: false },
      { id: 'secondaryKeywords', label: 'Secondary Keywords (optional)', placeholder: 'e.g., DGR certification, hazmat compliance', multiline: true, required: false },
      { id: 'contentGoal', label: 'Content Goal (optional)', placeholder: 'e.g., Drive enrollments for Category 6 course', multiline: true, required: false },
    ],
  },
  '7': {
    name: 'Content Expansion',
    description: 'Expand a content section with more detail and SEO optimization',
    iconName: 'FileText',
    category: 'content',
    fields: [
      { id: 'sectionUrl', label: 'Page URL (optional)', placeholder: 'e.g., https://dgtraining.com/iata-training/', required: false },
      { id: 'section', label: 'Current Section (optional if URL provided)', placeholder: 'Paste the content section to expand...', multiline: true, rows: 6, required: false },
      { id: 'targetLength', label: 'Target Word Count (optional)', placeholder: 'e.g., 800 words', required: false },
      { id: 'keywords', label: 'Focus Keywords (optional)', placeholder: 'e.g., lithium battery shipping, UN3480', multiline: true, required: false },
      { id: 'userIntent', label: 'User Intent (optional)', placeholder: 'e.g., Understanding lithium battery shipping', multiline: true, required: false },
    ],
  },
  '8': {
    name: 'Meta Description Review',
    description: "Improve existing meta descriptions for TDG's brand",
    iconName: 'CheckCircle',
    category: 'meta',
    fields: [
      { id: 'metaDescriptions', label: 'Existing Meta Descriptions *', placeholder: 'Paste meta descriptions to improve...', multiline: true, rows: 5, required: true },
      { id: 'business', label: 'Your Business', placeholder: 'Transportation Development Group', defaultValue: 'Transportation Development Group', required: false },
      { id: 'brandVoice', label: 'Brand Voice *', placeholder: 'e.g., Professional yet approachable', required: true },
      { id: 'audience', label: 'Target Audience *', placeholder: 'e.g., Logistics professionals, compliance managers', required: true },
    ],
  },
  '9': {
    name: 'FAQ Refinement',
    description: 'Customize generic FAQs with TDG-specific details',
    iconName: 'HelpCircle',
    category: 'faq',
    fields: [
      { id: 'faqs', label: 'AI-Generated FAQs *', placeholder: 'Paste FAQs to refine...', multiline: true, rows: 8, required: true },
      { id: 'specificServices', label: 'Your Specific Services *', placeholder: 'e.g., IATA Cat 6, Cat 11, IMDG', multiline: true, required: true },
      { id: 'policies', label: 'Company Policies *', placeholder: 'e.g., 24-month validity, group discounts', multiline: true, required: true },
      { id: 'contactInfo', label: 'Contact Information *', placeholder: 'e.g., support@dgtraining.com', required: true },
      { id: 'tone', label: 'Conversational Tone *', placeholder: 'e.g., Friendly but professional', required: true },
    ],
  },
  '10': {
    name: 'Focus Keyphrase Analyzer',
    description: 'Analyze page optimization for your target focus keyphrase',
    iconName: 'Search',
    category: 'content',
    fields: [
      { id: 'analyzeUrl', label: 'Page URL *', placeholder: 'e.g., https://dgtraining.com/iata-training/', required: true },
      { id: 'focusKeyphrase', label: 'Focus Keyphrase *', placeholder: 'e.g., iata certification online', required: true },
      { id: 'synonyms', label: 'Synonyms/Related (optional)', placeholder: 'e.g., iata dg training, dangerous goods certification', multiline: true, rows: 2, required: false },
    ],
  },
  '11': {
    name: 'Blog Post Generator',
    description: 'Create comprehensive, SEO-optimized blog posts on DG training topics',
    iconName: 'PenTool',
    category: 'advanced',
    fields: [
      { id: 'blogTopic', label: 'Blog Topic/Keyword *', placeholder: 'e.g., lithium battery shipping regulations 2025', required: true },
      { id: 'blogAngle', label: 'Angle/Approach (optional)', placeholder: 'e.g., beginner guide, regulatory update, how-to, case study', required: false },
      { id: 'targetAudience', label: 'Target Audience (optional)', placeholder: 'e.g., logistics professionals, compliance officers, new shippers', required: false },
      { id: 'wordCount', label: 'Target Word Count (optional)', placeholder: 'e.g., 1500 words (default: 1200-1500)', required: false },
      { id: 'includeTrending', label: 'Research Trending Topics?', type: 'checkbox', defaultValue: 'true', required: false },
    ],
  },
  '12': {
    name: 'Blog Topic Research',
    description: 'Research trending topics and generate blog post ideas with keyword opportunities',
    iconName: 'Lightbulb',
    category: 'advanced',
    fields: [
      { id: 'researchArea', label: 'Research Area *', placeholder: 'e.g., IATA regulations, lithium batteries, hazmat compliance', required: true },
      { id: 'competitorUrls', label: 'Competitor URLs (optional)', placeholder: 'Paste competitor blog URLs to analyze their topics', multiline: true, rows: 3, required: false },
      { id: 'numberOfIdeas', label: 'Number of Ideas', placeholder: '10', defaultValue: '10', required: false },
    ],
  },
  '13': {
    name: 'Landing Page Builder (Beta)',
    description: 'Generate fast-loading HTML landing page with TDG branding, optimized for conversions',
    iconName: 'Layout',
    category: 'advanced',
    fields: [
      {
        id: 'trainingCourse',
        label: 'Training Course *',
        type: 'select',
        required: true,
        options: [
          { value: '', label: 'Select a course...' },
          { value: 'IATA Category 6 - Shippers', label: 'IATA Category 6 - Shippers' },
          { value: 'IATA Category 3 - Freight Forwarders', label: 'IATA Category 3 - Freight Forwarders' },
          { value: 'IATA Category 1 - Operators', label: 'IATA Category 1 - Operators' },
          { value: 'IATA Recurrent Training', label: 'IATA Recurrent Training' },
          { value: 'DOT Hazmat General Awareness', label: 'DOT Hazmat General Awareness' },
          { value: 'DOT Hazmat Function-Specific', label: 'DOT Hazmat Function-Specific' },
          { value: 'DOT 49 CFR Ground Shipper', label: 'DOT 49 CFR Ground Shipper' },
          { value: 'IMDG Code - Ocean Shipping', label: 'IMDG Code - Ocean Shipping' },
          { value: 'Lithium Battery Shipping', label: 'Lithium Battery Shipping' },
          { value: 'Multimodal DG Training', label: 'Multimodal DG Training' },
          { value: 'Dry Ice Shipping', label: 'Dry Ice Shipping' },
          { value: 'Biological Substances (UN3373)', label: 'Biological Substances (UN3373)' },
        ],
      },
      {
        id: 'buyerPersona',
        label: 'Buyer Persona *',
        type: 'select',
        required: true,
        options: [
          { value: '', label: 'Select a buyer persona...' },
          { value: 'compliance-carol', label: 'Compliance Carol (Strategic Partner)' },
          { value: 'crisis-chris', label: 'Crisis Chris (Crisis Responder)' },
          { value: 'director-derek', label: 'Director Derek (Enterprise)' },
          { value: 'checkbox-charlie', label: 'Checkbox Charlie (Transactional)' },
          { value: 'irate-irene', label: 'Irate Irene (Convinced-by-Competitor)' },
        ],
      },
      {
        id: 'marketSegment',
        label: 'Market Segment *',
        type: 'select',
        required: true,
        options: [
          { value: '', label: 'Select a market segment...' },
          { value: 'maker', label: 'MAKER (Offerer) - Manufacturers, distributors, e-commerce' },
          { value: 'mover', label: 'MOVER (Carrier) - Freight forwarders, 3PLs, airlines' },
        ],
      },
      {
        id: 'urgencyLevel',
        label: 'Urgency Context',
        type: 'select',
        required: false,
        options: [
          { value: '', label: 'No specific urgency' },
          { value: 'Certificate expiring soon - needs renewal ASAP', label: 'Certificate Expiring' },
          { value: 'Shipment rejected by carrier - needs cert to ship', label: 'Carrier Rejection' },
          { value: 'Audit coming up - needs compliance documentation', label: 'Upcoming Audit' },
          { value: 'New job requirement - must get certified to start', label: 'Job Requirement' },
          { value: 'Expanding to DG shipping - getting started', label: 'New to DG Shipping' },
        ],
      },
      { id: 'promotionOffer', label: 'Promotion/Offer (optional)', placeholder: 'e.g., 20% off for groups of 5+, Free DGR manual included', required: false },
      { id: 'courseUrl', label: 'Course URL for CTA *', placeholder: 'https://dgtraining.com/course-name/', required: true },
      { id: 'coursePrice', label: 'Course Price', placeholder: 'e.g., $199, $149 (sale)', required: false },
    ],
  },
};
